//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeHoursDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class officehours_schedule
    {
        public long schedule_id { get; set; }
        public string faculty_email { get; set; }
        public string schedule_note { get; set; }
        public System.DateTime schedule_start { get; set; }
        public System.DateTime schedule_end { get; set; }
        public string schedule_color { get; set; }
        public string schedule_group { get; set; }
    }
}
