//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeHoursDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class officehours_messages
    {
        public long message_id { get; set; }
        public string faculty_mail { get; set; }
        public string student_id { get; set; }
        public string student_Name { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<int> is_archived { get; set; }
    }
}
