//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeHoursDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class officehoursEntities : DbContext
    {
        public officehoursEntities()
            : base("name=officehoursEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<officehours_Admin_Users> officehours_Admin_Users { get; set; }
        public virtual DbSet<officehours_faculty> officehours_faculty { get; set; }
        public virtual DbSet<officehours_schedule> officehours_schedule { get; set; }
        public virtual DbSet<officehours_messages> officehours_messages { get; set; }
    }
}
