//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeHoursDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class officehours_faculty
    {
        public int member_id { get; set; }
        public string first_Name { get; set; }
        public string last_Name { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> account_status { get; set; }
        public string auth_code { get; set; }
        public string phone_number { get; set; }
    }
}
