//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeHoursDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class officehours_Admin_Users
    {
        public int Admin_User_Id { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
    }
}
